# Generated by Django 4.2.28 on 2026-02-25 11:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('match_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('match_type', models.CharField(db_index=True, max_length=10)),
                ('match_date', models.DateField(db_index=True)),
                ('venue', models.CharField(db_index=True, max_length=100)),
                ('event_name', models.CharField(blank=True, max_length=100, null=True)),
                ('toss_winner', models.CharField(max_length=50)),
                ('toss_decision', models.CharField(max_length=10)),
                ('match_winner', models.CharField(blank=True, max_length=50, null=True)),
                ('win_margin_runs', models.IntegerField(blank=True, null=True)),
                ('win_margin_wickets', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('player_id', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('full_name', models.CharField(db_index=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='InningMetadata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inning_number', models.IntegerField()),
                ('batting_team', models.CharField(max_length=50)),
                ('target_runs', models.IntegerField(blank=True, null=True)),
                ('powerplay_type', models.CharField(blank=True, max_length=20, null=True)),
                ('powerplay_start', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('powerplay_end', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='innings_meta', to='cricket.match')),
            ],
        ),
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inning_number', models.IntegerField()),
                ('over_number', models.IntegerField(db_index=True)),
                ('ball_number', models.IntegerField()),
                ('batter_runs', models.IntegerField(default=0)),
                ('extra_runs', models.IntegerField(default=0)),
                ('total_runs', models.IntegerField(default=0)),
                ('is_wide', models.BooleanField(default=False)),
                ('is_noball', models.BooleanField(default=False)),
                ('is_wicket', models.BooleanField(default=False)),
                ('dismissal_kind', models.CharField(blank=True, max_length=30, null=True)),
                ('batter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='balls_faced', to='cricket.player')),
                ('bowler', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='balls_bowled', to='cricket.player')),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='cricket.match')),
                ('non_striker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='balls_at_non_striker', to='cricket.player')),
                ('player_out', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dismissals', to='cricket.player')),
            ],
            options={
                'indexes': [models.Index(fields=['batter', 'over_number'], name='cricket_del_batter__f33b7d_idx'), models.Index(fields=['bowler', 'over_number'], name='cricket_del_bowler__c32c2e_idx')],
            },
        ),
    ]
