# Generated by Django 4.2.28 on 2026-02-25 12:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cricket', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inningmetadata',
            name='powerplay_end',
        ),
        migrations.RemoveField(
            model_name='inningmetadata',
            name='powerplay_start',
        ),
        migrations.RemoveField(
            model_name='inningmetadata',
            name='powerplay_type',
        ),
        migrations.CreateModel(
            name='Powerplay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inning_number', models.IntegerField()),
                ('powerplay_type', models.CharField(max_length=20)),
                ('start_over', models.DecimalField(decimal_places=1, max_digits=4)),
                ('end_over', models.DecimalField(decimal_places=1, max_digits=4)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='powerplays', to='cricket.match')),
            ],
            options={
                'indexes': [models.Index(fields=['match', 'inning_number'], name='cricket_pow_match_i_033b2a_idx')],
            },
        ),
    ]
