# Generated by Django 4.2.28 on 2026-02-25 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cricket', '0002_remove_inningmetadata_powerplay_end_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='team_a',
            field=models.CharField(db_index=True, default='Unknown', max_length=50),
        ),
        migrations.AddField(
            model_name='match',
            name='team_b',
            field=models.CharField(db_index=True, default='Unknown', max_length=50),
        ),
    ]
