# Generated by Django 4.2.28 on 2026-02-25 17:50

from django.db import migrations, models
import pgvector.django


class Migration(migrations.Migration):

    dependencies = [
        ('cricket', '0003_match_team_a_match_team_b'),
    ]

    operations = [
        migrations.CreateModel(
            name='SemanticCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_question', models.TextField()),
                ('question_embedding', pgvector.django.VectorField(dimensions=768)),
                ('response_payload', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
