# Generated by Django 4.2.28 on 2026-03-08 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cricket', '0004_semanticcache'),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
            -- ==========================================
            -- VIEW 1: MATCH SUMMARY (The Game Level)
            -- ==========================================
            CREATE MATERIALIZED VIEW vw_match_summary AS
            SELECT 
                m.match_id,
                EXTRACT(YEAR FROM m.match_date) AS season_year,
                m.match_date,
                m.venue,
                m.team_a,
                m.team_b,
                m.match_winner,
                
                -- EXTENSIBILITY HOOKS: 
                -- Replace these NULLs with actual columns once you add them to your Django models.
                NULL AS team_a_captain,
                NULL AS team_b_captain,
                NULL AS toss_winner,
                NULL AS toss_decision,
                NULL AS win_margin_type,
                NULL AS win_margin_amount,
                NULL AS player_of_match
            FROM 
                cricket_match m;

            CREATE UNIQUE INDEX idx_vw_match_summary_id ON vw_match_summary(match_id);


            -- ==========================================
            -- VIEW 2: DELIVERY ANALYTICS (One Big Table)
            -- ==========================================
            CREATE MATERIALIZED VIEW vw_delivery_analytics AS
            SELECT 
                d.match_id,
                m.match_date,
                EXTRACT(YEAR FROM m.match_date) AS season_year,
                d.inning_number,
                
                -- Smart Deduction: Batting and Bowling Teams
                CASE WHEN d.inning_number = 1 THEN m.team_a ELSE m.team_b END AS batting_team,
                CASE WHEN d.inning_number = 1 THEN m.team_b ELSE m.team_a END AS bowling_team,
                
                -- Smart Phase of Play (0-5 PP, 6-14 Middle, 15-19 Death)
                CASE 
                    WHEN d.over_number <= 5 THEN 'Powerplay'
                    WHEN d.over_number BETWEEN 6 AND 14 THEN 'Middle'
                    ELSE 'Death'
                END AS phase_of_play,
                
                -- Pre-Joined Player Names (Kills LLM Join Hallucinations)
                p_bat.full_name AS batter_name,
                p_bow.full_name AS bowler_name,
                NULL AS non_striker_name, -- Extensibility Hook
                
                d.over_number,
                d.ball_number,
                
                -- Core Runs
                d.batter_runs,
                d.extra_runs,
                d.total_runs,
                
                -- Smart Boundary Math
                CASE WHEN d.batter_runs = 4 THEN 1 ELSE 0 END AS is_four,
                CASE WHEN d.batter_runs = 6 THEN 1 ELSE 0 END AS is_six,
                CASE WHEN d.batter_runs IN (4, 6) THEN 1 ELSE 0 END AS is_boundary,
                
                -- Smart Delivery Math (Fixes Over & Strike Rate calculations)
                CASE WHEN d.is_wide = FALSE AND d.is_noball = FALSE THEN 1 ELSE 0 END AS is_legal_ball,
                CASE WHEN d.total_runs = 0 AND d.is_wide = FALSE AND d.is_noball = FALSE THEN 1 ELSE 0 END AS is_dot_ball,
                
                -- Smart Wicket Math (Fixes Bowling Average calculations)
                CASE WHEN d.is_wicket = TRUE THEN 1 ELSE 0 END AS is_wicket,
                CASE WHEN d.is_wicket = TRUE AND d.dismissal_kind NOT IN ('run out', 'retired hurt', 'obstructing the field') THEN 1 ELSE 0 END AS is_bowler_wicket,
                d.dismissal_kind,
                
                -- Extensibility Hooks for Fielding
                NULL AS player_dismissed,
                NULL AS fielder_name
                
            FROM 
                cricket_delivery d
            JOIN 
                cricket_match m ON d.match_id = m.match_id
            JOIN 
                cricket_player p_bat ON d.batter_id = p_bat.player_id
            JOIN 
                cricket_player p_bow ON d.bowler_id = p_bow.player_id;

            -- INDEXES FOR INSTANT LLM QUERYING
            CREATE INDEX idx_vw_delivery_batter ON vw_delivery_analytics(batter_name);
            CREATE INDEX idx_vw_delivery_bowler ON vw_delivery_analytics(bowler_name);
            CREATE INDEX idx_vw_delivery_match ON vw_delivery_analytics(match_id);
            CREATE INDEX idx_vw_delivery_teams ON vw_delivery_analytics(batting_team, bowling_team);
            """,
            
            # Reverse SQL so you can undo the migration safely
            reverse_sql="""
            DROP MATERIALIZED VIEW IF EXISTS vw_delivery_analytics;
            DROP MATERIALIZED VIEW IF EXISTS vw_match_summary;
            """
        )
    ]
