# Generated by Django 4.2.28 on 2026-03-08 11:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cricket', '0005_auto_20260308_1053'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='fielder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fielding_dismissals', to='cricket.player'),
        ),
        migrations.AddField(
            model_name='match',
            name='player_of_match',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='team_a_captain',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='team_b_captain',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
