# Generated by Django 4.2.28 on 2026-03-08 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cricket', '0007_auto_20260308_1103'),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
            DROP MATERIALIZED VIEW IF EXISTS vw_delivery_analytics;

            CREATE MATERIALIZED VIEW vw_delivery_analytics AS
            SELECT 
                d.match_id,
                m.match_date,
                EXTRACT(YEAR FROM m.match_date) AS season_year,
                d.inning_number,
                
                im.batting_team AS batting_team,
                
                CASE WHEN im.batting_team = m.team_a THEN m.team_b ELSE m.team_a END AS bowling_team,
                
                CASE 
                    WHEN d.over_number <= 5 THEN 'Powerplay'
                    WHEN d.over_number BETWEEN 6 AND 14 THEN 'Middle'
                    ELSE 'Death'
                END AS phase_of_play,
                p_bat.full_name AS batter_name,
                p_bow.full_name AS bowler_name,
                p_non.full_name AS non_striker_name,
                d.over_number,
                d.ball_number,
                d.batter_runs,
                d.extra_runs,
                d.total_runs,
                CASE WHEN d.batter_runs = 4 THEN 1 ELSE 0 END AS is_four,
                CASE WHEN d.batter_runs = 6 THEN 1 ELSE 0 END AS is_six,
                CASE WHEN d.batter_runs IN (4, 6) THEN 1 ELSE 0 END AS is_boundary,
                CASE WHEN d.is_wide = FALSE AND d.is_noball = FALSE THEN 1 ELSE 0 END AS is_legal_ball,
                CASE WHEN d.total_runs = 0 AND d.is_wide = FALSE AND d.is_noball = FALSE THEN 1 ELSE 0 END AS is_dot_ball,
                CASE WHEN d.is_wicket = TRUE THEN 1 ELSE 0 END AS is_wicket,
                CASE WHEN d.is_wicket = TRUE AND d.dismissal_kind NOT IN ('run out', 'retired hurt', 'obstructing the field') THEN 1 ELSE 0 END AS is_bowler_wicket,
                d.dismissal_kind,
                p_out.full_name AS player_dismissed,
                p_field.full_name AS fielder_name
            FROM cricket_delivery d
            JOIN cricket_match m ON d.match_id = m.match_id
            
            -- THE CRUCIAL NEW JOIN
            JOIN cricket_inningmetadata im ON d.match_id = im.match_id AND d.inning_number = im.inning_number
            
            JOIN cricket_player p_bat ON d.batter_id = p_bat.player_id
            JOIN cricket_player p_bow ON d.bowler_id = p_bow.player_id
            LEFT JOIN cricket_player p_non ON d.non_striker_id = p_non.player_id
            LEFT JOIN cricket_player p_out ON d.player_out_id = p_out.player_id
            LEFT JOIN cricket_player p_field ON d.fielder_id = p_field.player_id;

            CREATE INDEX idx_vw_delivery_batter ON vw_delivery_analytics(batter_name);
            CREATE INDEX idx_vw_delivery_bowler ON vw_delivery_analytics(bowler_name);
            CREATE INDEX idx_vw_delivery_match ON vw_delivery_analytics(match_id);
            CREATE INDEX idx_vw_delivery_teams ON vw_delivery_analytics(batting_team, bowling_team);
            """
        )
    ]
