# Generated by Django 4.2.28 on 2026-03-08 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cricket', '0008_auto_20260308_1125'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='event_match_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='event_stage',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
