# Generated by Django 4.2.28 on 2026-03-08 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cricket', '0009_match_event_match_number_match_event_stage'),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
            DROP MATERIALIZED VIEW IF EXISTS vw_match_summary;

            CREATE MATERIALIZED VIEW vw_match_summary AS
            SELECT 
                m.match_id,
                EXTRACT(YEAR FROM m.match_date) AS season_year,
                m.match_date,
                m.venue,
                m.team_a,
                m.team_b,
                m.match_winner,
                m.team_a_captain,
                m.team_b_captain,
                m.toss_winner,
                m.toss_decision,
                CASE WHEN m.win_margin_runs > 0 THEN 'runs' WHEN m.win_margin_wickets > 0 THEN 'wickets' ELSE 'other' END AS win_margin_type,
                COALESCE(m.win_margin_runs, m.win_margin_wickets) AS win_margin_amount,
                m.player_of_match,
                m.event_name,
                m.event_stage,
                m.event_match_number,
                m.match_type
            FROM cricket_match m;

            CREATE UNIQUE INDEX idx_vw_match_summary_id ON vw_match_summary(match_id);
            """
        )
    ]