# Generated by Django 4.2.29 on 2026-03-14 10:07

from django.db import migrations
from pgvector.django import VectorExtension


class Migration(migrations.Migration):

    dependencies = [
        ('cricket', '0010_auto_20260308_1145'),
    ]

    operations = [
        VectorExtension(),
    ]
