# Generated by Django 4.2.29 on 2026-03-14 10:07

from django.db import migrations, models
import pgvector.django


class Migration(migrations.Migration):

    dependencies = [
        ('cricket', '0011_enable_vector_extension'),
    ]

    operations = [
        migrations.CreateModel(
            name='SmartSQLExample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(help_text="The natural language question (e.g., 'strike rate of virat kohli')", max_length=500)),
                ('sql_query', models.TextField(help_text='The exact SQL syntax to use as a template')),
                ('embedding', pgvector.django.VectorField(blank=True, dimensions=768, help_text='The vector representation of the question', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
