# Generated by Django 4.2.29 on 2026-04-04 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cricket', '0014_chatsession'),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
            -- 1. The Batter Stats Materialized View
            DROP MATERIALIZED VIEW IF EXISTS vw_batter_stats CASCADE;
            
            CREATE MATERIALIZED VIEW vw_batter_stats AS
            WITH MatchMilestones AS (
                SELECT 
                    batter_name, 
                    match_id, 
                    SUM(batter_runs) as match_runs
                FROM vw_delivery_analytics
                GROUP BY batter_name, match_id
            ),
            AggMilestones AS (
                SELECT
                    batter_name,
                    MAX(match_runs) AS highest_score,
                    SUM(CASE WHEN match_runs >= 50 AND match_runs < 100 THEN 1 ELSE 0 END) AS fifties,
                    SUM(CASE WHEN match_runs >= 100 THEN 1 ELSE 0 END) AS centuries
                FROM MatchMilestones
                GROUP BY batter_name
            )
            SELECT 
                d.batter_name AS player_name,
                COUNT(DISTINCT d.match_id) AS innings_batted,
                SUM(d.batter_runs) AS total_runs,
                SUM(d.is_legal_ball) AS balls_faced,
                SUM(CASE WHEN d.player_dismissed = d.batter_name THEN 1 ELSE 0 END) AS dismissals,
                SUM(d.is_four) AS fours,
                SUM(d.is_six) AS sixes,
                m.highest_score,
                m.fifties,
                m.centuries
            FROM vw_delivery_analytics d
            JOIN AggMilestones m ON d.batter_name = m.batter_name
            GROUP BY d.batter_name, m.highest_score, m.fifties, m.centuries;

            CREATE UNIQUE INDEX idx_vw_batter_stats_name ON vw_batter_stats(player_name);


            -- 2. The Bowler Stats Materialized View
            DROP MATERIALIZED VIEW IF EXISTS vw_bowler_stats CASCADE;
            
            CREATE MATERIALIZED VIEW vw_bowler_stats AS
            SELECT 
                bowler_name AS player_name,
                COUNT(DISTINCT match_id) AS innings_bowled,
                SUM(is_bowler_wicket) AS total_wickets,
                SUM(total_runs) AS runs_conceded,
                SUM(is_legal_ball) AS legal_balls_bowled,
                ROUND((SUM(total_runs) * 6.0) / NULLIF(SUM(is_legal_ball), 0), 2) AS bowling_economy,
                ROUND(SUM(total_runs) * 1.0 / NULLIF(SUM(is_bowler_wicket), 0), 2) AS bowling_average
            FROM vw_delivery_analytics
            GROUP BY bowler_name;

            CREATE UNIQUE INDEX idx_vw_bowler_stats_name ON vw_bowler_stats(player_name);


            -- 3. The Master All-Rounder Materialized View
            DROP MATERIALIZED VIEW IF EXISTS vw_player_master CASCADE;
            
            CREATE MATERIALIZED VIEW vw_player_master AS
            SELECT 
                COALESCE(bat.player_name, bowl.player_name) AS player_name,
                
                -- Batting
                COALESCE(bat.innings_batted, 0) AS innings_batted,
                COALESCE(bat.total_runs, 0) AS total_runs,
                COALESCE(bat.highest_score, 0) AS highest_score,
                ROUND((bat.total_runs * 100.0) / NULLIF(bat.balls_faced, 0), 2) AS strike_rate,
                
                -- Bowling
                COALESCE(bowl.innings_bowled, 0) AS innings_bowled,
                COALESCE(bowl.total_wickets, 0) AS total_wickets,
                COALESCE(bowl.bowling_economy, 0.00) AS economy_rate,
                COALESCE(bowl.bowling_average, 0.00) AS bowling_average

            FROM vw_batter_stats bat
            FULL OUTER JOIN vw_bowler_stats bowl 
                ON bat.player_name = bowl.player_name;

            CREATE UNIQUE INDEX idx_vw_player_master_name ON vw_player_master(player_name);
            """,
            
            reverse_sql="""
            DROP MATERIALIZED VIEW IF EXISTS vw_player_master;
            DROP MATERIALIZED VIEW IF EXISTS vw_bowler_stats;
            DROP MATERIALIZED VIEW IF EXISTS vw_batter_stats;
            """
        )
    ]
